### DISCUSSION TITLE
v-for rendering again

### DISCUSSION THREAD

**Discussion by halivert** [vuejs/petite-vue#166] [Q&A]
I have [this pen](https://codepen.io/halivert/pen/poLNBPB), where I create a list with a v-for, but when I update the list (remove an element clicking on it), then the next elements render again i.e. if you click the 5, then the 6, 7, and so on, are re-rendered

```html
<ul v-scope>
	<li v-for="item in items" :key="item" class="animation" @click="remove(item)">
		{{ item }}
	</li>
</ul>
```

```js
import { createApp } from "https://cdn.skypack.dev/petite-vue@0.4.1";

createApp({
	items: Array.from({ length: 10 }, (_, i) => i + 1),
	remove(item) {
		this.items = this.items.filter((i) => i !== item);
	}
}).mount("ul");
```

```css
.animation {
	animation: fade-in 1s forwards;
}

@keyframes fade-in {
	from {
		opacity: 0;
	}
	to {
		opacity: 1;
	}
}
```

**Am I doing something wrong?**
_I have setted the keys for the elements in the v-for_
